// Seagonia Hotel Constants
// Name: Seagonia (Sea + Gonia = Sea Corner)
// Location: Pogonia village, near Paleros, Aitoloakarnania, Ionian Sea, Greece

export const HOTEL = {
  name: 'Seagonia',
  tagline: 'Your Corner by the Sea',
  location: {
    village: 'Pogonia',
    nearCity: 'Paleros',
    region: 'Aitoloakarnania',
    sea: 'Ionian Sea',
    country: 'Greece',
    coords: {
      lat: 38.7833,
      lng: 20.8833,
    },
  },
  contact: {
    phone: import.meta.env.VITE_HOTEL_PHONE,
    email: import.meta.env.VITE_HOTEL_EMAIL,
    address: import.meta.env.VITE_HOTEL_ADDRESS,
  },
  social: {
    instagram: 'https://www.instagram.com/seagoniahotel',
    facebook: 'https://www.facebook.com/seagoniahotel',
  },
  totalRooms: 58,
}

export const ROOMS = [
  {
    id: 'garden-room',
    type: 'A',
    name: 'Garden Room',
    slug: 'garden-room',
    count: 16,
    floor: 'Ground Floor',
    maxGuests: 2,
    bedOptions: ['King Bed', 'Twin Beds'],
    highlight: 'Private Garden',
    description:
      'Nestled on the ground floor, these serene rooms open directly onto a lush private garden. Wake to birdsong and step outside into your own green sanctuary. Perfect for those who love a connection with nature.',
    amenities: [
      'Private Garden',
      'Outdoor Sitting Area',
      'King Bed or Twin Beds',
      'A/C & Heating',
      '50" Smart TV',
      'Mini Bar',
      'Espresso Machine',
      'Kettle',
      'Hair Dryer',
      'Iron & Ironing Board',
      'Safe',
      'Free WiFi',
      'Reading Lights',
    ],
    image: 'roomGarden',
  },
  {
    id: 'swim-up-room',
    type: 'B',
    name: 'Swim-Up Room',
    slug: 'swim-up-room',
    count: 12,
    floor: 'Ground Floor',
    maxGuests: 2,
    bedOptions: ['King Bed', 'Twin Beds'],
    highlight: 'Private Pool Access',
    description:
      'Step from your room directly into the pool. These exclusive ground-floor rooms offer unrivalled access to the water, blending indoor comfort with an outdoor aquatic lifestyle. Ideal for those who want to make every moment count.',
    amenities: [
      'Direct Pool Access',
      'Outdoor Sitting Area',
      'King Bed or Twin Beds',
      'A/C & Heating',
      '50" Smart TV',
      'Mini Bar',
      'Espresso Machine',
      'Kettle',
      'Hair Dryer',
      'Iron & Ironing Board',
      'Safe',
      'Free WiFi',
      'Reading Lights',
    ],
    image: 'roomSwimUp',
  },
  {
    id: 'accessible-room',
    type: 'C',
    name: 'Accessible Garden Room',
    slug: 'accessible-room',
    count: 3,
    floor: 'Ground Floor',
    maxGuests: 2,
    bedOptions: ['King Bed', 'Twin Beds'],
    highlight: 'Fully Accessible with Garden',
    description:
      'Thoughtfully designed for all guests, these ground-floor rooms combine full accessibility with the tranquillity of a private garden. Every detail has been considered to ensure comfort and ease without compromise.',
    amenities: [
      'Private Garden',
      'Fully Accessible Design',
      'Outdoor Sitting Area',
      'King Bed or Twin Beds',
      'A/C & Heating',
      '50" Smart TV',
      'Mini Bar',
      'Espresso Machine',
      'Kettle',
      'Hair Dryer',
      'Iron & Ironing Board',
      'Safe',
      'Free WiFi',
      'Reading Lights',
    ],
    image: 'roomGarden',
  },
  {
    id: 'balcony-room',
    type: 'D',
    name: 'Balcony Room',
    slug: 'balcony-room',
    count: 23,
    floor: '1st Floor',
    maxGuests: 2,
    bedOptions: ['King Bed', 'Twin Beds'],
    highlight: 'Sea & Mountain Views',
    description:
      'Elevated on the first floor with a private balcony, these rooms invite you to soak in panoramic views of the Ionian Sea and surrounding mountains. Sip your morning coffee as the sun rises over the water — a vista you will never tire of.',
    amenities: [
      'Private Balcony',
      'Sea & Mountain Views',
      'Outdoor Sitting Area',
      'King Bed or Twin Beds',
      'A/C & Heating',
      '50" Smart TV',
      'Mini Bar',
      'Espresso Machine',
      'Kettle',
      'Hair Dryer',
      'Iron & Ironing Board',
      'Safe',
      'Free WiFi',
      'Reading Lights',
    ],
    image: 'roomBalcony',
  },
  {
    id: 'terrace-suite',
    type: 'E',
    name: 'Terrace Suite',
    slug: 'terrace-suite',
    count: 3,
    floor: '1st Floor',
    maxGuests: 2,
    bedOptions: ['King Bed', 'Twin Beds'],
    highlight: 'Spacious Private Terrace',
    description:
      'Generous in space and spirit, these first-floor suites feature expansive private terraces — an outdoor living room in the sky. Enjoy al fresco dining, evening cocktails, or simply stargazing above the Ionian coast.',
    amenities: [
      'Spacious Private Terrace',
      'Outdoor Sitting & Dining Area',
      'King Bed or Twin Beds',
      'A/C & Heating',
      '50" Smart TV',
      'Mini Bar',
      'Espresso Machine',
      'Kettle',
      'Hair Dryer',
      'Iron & Ironing Board',
      'Safe',
      'Free WiFi',
      'Reading Lights',
    ],
    image: 'roomTerrace',
  },
  {
    id: 'seagonia-suite',
    type: 'F',
    name: 'Seagonia Suite',
    slug: 'seagonia-suite',
    count: 1,
    floor: '1st Floor',
    maxGuests: 4,
    bedOptions: ['King Bed', 'Twin Beds'],
    highlight: 'Premium Two-Room Suite',
    description:
      'The pinnacle of Seagonia hospitality. This singular premium suite spans two rooms on the first floor, offering the ultimate in space, privacy and luxury for up to four guests. Every indulgence has been curated for those who expect nothing less than the finest.',
    amenities: [
      'Two-Room Suite',
      'Private Terrace',
      'Panoramic Sea View',
      'Outdoor Sitting & Dining Area',
      'King Bed or Twin Beds',
      'A/C & Heating',
      '50" Smart TV',
      'Mini Bar',
      'Espresso Machine',
      'Kettle',
      'Hair Dryer',
      'Iron & Ironing Board',
      'Safe',
      'Free WiFi',
      'Reading Lights',
      'Premium Amenities',
    ],
    image: 'roomSuite',
    featured: true,
  },
]

// Icon names correspond to lucide-react icon component names
export const AMENITIES = [
  {
    id: 'pool',
    name: 'Swimming Pool',
    icon: 'Waves',
    description: 'Central heated pool + 3 swim-up pools',
  },
  {
    id: 'beach',
    name: 'Beach Access',
    icon: 'Umbrella',
    description: 'Sandy beach just 80m away, 500m long',
  },
  {
    id: 'restaurant',
    name: 'Galià Restaurant',
    icon: 'UtensilsCrossed',
    description: 'Rooftop Mediterranean dining',
  },
  {
    id: 'lounge',
    name: 'Seagonia Lounge',
    icon: 'Coffee',
    description: 'Breakfast buffet & Mediterranean lunch',
  },
  {
    id: 'pool-bar',
    name: 'Pool Bar',
    icon: 'Wine',
    description: 'All-day drinks & snacks',
  },
  {
    id: 'gym',
    name: 'Technogym Fitness',
    icon: 'Dumbbell',
    description: 'Indoor gym + outdoor shaded fitness',
  },
  {
    id: 'massage',
    name: 'Outdoor Massage',
    icon: 'Heart',
    description: 'Covered massage space for two',
  },
  {
    id: 'yoga',
    name: 'Yoga & Pilates',
    icon: 'Flower2',
    description: 'Outdoor shaded area',
  },
  {
    id: 'swimming',
    name: 'Open Water Swimming',
    icon: 'Waves',
    description: '500m beach, calm Ionian waters',
  },
  {
    id: 'boat',
    name: 'Boat Excursions',
    icon: 'Ship',
    description: 'Ionian islands trips via Ionian Escape',
  },
  {
    id: 'cooking',
    name: 'Cooking Classes',
    icon: 'ChefHat',
    description: 'Farm-to-table hands-on classes',
  },
  {
    id: 'beekeeping',
    name: 'Beekeeping',
    icon: 'Bug',
    description: 'Honey harvesting experience',
  },
  {
    id: 'parking',
    name: 'Free Parking',
    icon: 'ParkingCircle',
    description: 'Private on-site parking',
  },
  {
    id: 'wifi',
    name: 'Free WiFi',
    icon: 'Wifi',
    description: 'High-speed throughout',
  },
  {
    id: 'farm',
    name: 'Farm to Table',
    icon: 'Leaf',
    description: 'Own farm supplying restaurants',
  },
  {
    id: 'spa',
    name: 'PURE Spa',
    icon: 'Sparkles',
    description: 'Nearby wellness center with 3 treatment rooms',
  },
]

export const EXPERIENCES = [
  {
    id: 'boat-trips',
    name: 'Boat Trips to Ionian Islands',
    description:
      'Sail the crystalline waters of the Ionian Sea and discover the legendary islands of Lefkada, Meganisi and beyond. Arrange your journey through our partner Ionian Escape.',
    image: 'boatTrip',
    icon: 'Ship',
  },
  {
    id: 'cooking-classes',
    name: 'Cooking Classes & Farm Experience',
    description:
      'Learn the secrets of Greek cuisine with hands-on cooking classes using ingredients harvested from our own farm. A farm-to-table experience unlike any other.',
    image: 'cooking',
    icon: 'ChefHat',
  },
  {
    id: 'hiking',
    name: 'Hiking & Ancient Paleros',
    description:
      'Explore the rugged trails around Pogonia and discover the ancient ruins of Paleros. History, nature and breathtaking views await at every turn.',
    image: 'hiking',
    icon: 'Map',
  },
  {
    id: 'open-water',
    name: 'Open Water Swimming',
    description:
      'The 500-metre sandy beach just 80 metres from the hotel offers calm, clear Ionian waters ideal for open water swimming at any level.',
    image: 'beach',
    icon: 'Waves',
  },
  {
    id: 'wellness',
    name: 'Wellness & Spa',
    description:
      'Restore body and mind with outdoor yoga and pilates sessions, covered massage treatments for two, or a visit to the nearby PURE Spa wellness centre.',
    image: 'spa',
    icon: 'Sparkles',
  },
  {
    id: 'gastronomy',
    name: 'Wine & Gastronomy',
    description:
      'Dine at the Galià rooftop restaurant and savour Mediterranean cuisine paired with fine Greek wines, all with sweeping views of the Ionian coast.',
    image: 'restaurant',
    icon: 'Wine',
  },
]

export const PLACEHOLDER_IMAGES = {
  hero: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&auto=format&fit=crop',
  pool: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop',
  seaView: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&auto=format&fit=crop',
  roomGarden: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop',
  roomSwimUp: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&auto=format&fit=crop',
  roomBalcony: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop',
  roomTerrace: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&auto=format&fit=crop',
  roomSuite: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop',
  restaurant: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop',
  breakfast: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&auto=format&fit=crop',
  ionian: 'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&auto=format&fit=crop',
  beach: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop',
  yoga: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop',
  spa: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop',
  cooking: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop',
  fitness: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop',
  boatTrip: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800&auto=format&fit=crop',
  hiking: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&auto=format&fit=crop',
}
